### ISSUE TITLE
Curse.com now Curseforge.com

### ISSUE THREAD

**Issue by Smallinger** [Sumolari/WAM#2]
The Website curse.com has a new update, can you please update your Script ?

**Comment by Sumolari** [comment]
Fixed in c2112fee316beb223e7b35a1b1652e496c30bd34.

Please note that this hasn't been quite tested (I'm not currently a WoW player and don't have much time to maintain projects like this one) so it might be buggy.

**Edit:** version `0.0.4` includes this change and it's available in NPM:

```
npm install -g wow-am
```

Should install the new version.
